# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @author Boran Gao, \email{borang@umich.edu}
#' @title
#' CoMM Binary
#' @description
#' CoMM Binary to dissecting genetic contributions to complex disease by leveraging regulatory information.
#'
#' @param Y  trait vector.
#' @param Z  gene expression vector.
#' @param X_1  normalized genotype (cis-SNPs) matrix for eQTL.
#' @param X_2  normalized genotype (cis-SNPs) matrix for GWAS.
#' @param constr  indicator for constraint (alpha = 0 if constr = 1).
#'
#' @return List of model parameters
#' @export
CoMM_Binary <- function(Y, Z, X_1, X_2, constr) {
    .Call(`_CommBinary_CoMM_Binary`, Y, Z, X_1, X_2, constr)
}

